  on:
    push:
      branches:
          - main

  jobs:
    build:
        runs-on: ubuntu-latest


        steps:
           - uses: actions/checkout@v3
           - name: "login to Docker hun"
             run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_SECRET }}
           - name: "create image"
             run: docker build -t kilaney/task2Actions .

           - name: "push to docker"
             run: docker push kilanet/task2Actions