  on:
    push:
      branches:
          - main

  jobs:
    build:
        runs-on: ubuntu-latest


        steps:
           - name: 'testing git hub action'
             run: pwd
           - uses: actions/checkout@v3
           - name: 'list'
             run: ls